name: 👾 Deploy to Cloudflare pages. 

on: 
  push: 
    branches: 
      - main

jobs: 
  deploy: 
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Deploy to Cloudflare Pages
        uses: actions/checkout@v3

      - name: 🛠️ Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies. 
        run: |
          bun install

      - name: Build project
        run: |
          bun run build
      
      - name: Publish to Cloudflare pages
        uses: cloudflare/wrangler-action@v3
        with:
            apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
            accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
            command: |
              pages deploy out --project-name teoriacomputacion  --commit-dirty=true 
            workingDirectory: /
            gitHubToken: ${{ secrets.GITHUB_TOKEN }}
      